[package]
name = "image_processor"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
image = "0.25.9"
libloading = "0.9.0"
thiserror = "2.0.17"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt"] }
tracing = "0.1.44"
